[window]
opacity = 1

[colors]
draw_bold_text_with_bright_colors = true

[env]
LANG = "en_US.UTF-8"

[font]
size = 10.0

[font.bold]
family = "SauceCodePro Nerd Font"

[font.normal]
family = "Alacritty Font"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
mouse.mods = "Control"
mouse.enabled = true

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[scrolling]
history = 50000
